name: Pubby.co Login, Browse & Pick Kindle Unlimited Book & View On Amazon Automation

on:
  schedule:
    - cron: '*/10 * * * *'   # every 10 minutes
  workflow_dispatch:

jobs:
  login-pubby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm init -y
          npm install puppeteer puppeteer-core puppeteer-extra puppeteer-extra-plugin-stealth fs

      - name: Create Puppeteer script for Login, Browse & Pick Kindle Unlimited Book & View On Amazon
        run: |
          mkdir -p scripts screenshots
          cat > scripts/pubby-login-and-browse.js << 'EOL'
          const puppeteer = require('puppeteer-extra');
          const StealthPlugin = require('puppeteer-extra-plugin-stealth');
          const fs = require('fs');

          puppeteer.use(StealthPlugin());

          function sleep(ms) {
            return new Promise(r => setTimeout(r, ms));
          }

          async function safeScreenshot(page, path) {
            try {
              await page.screenshot({ path });
              console.log(`Screenshot taken: ${path}`);
            } catch (e) {
              console.error(`Screenshot error: ${e.message}`);
            }
          }

          async function loginAndBrowse(loginUrl, browseUrl, username, password) {
            let browser, page;
            try {
              console.log("Launching browser...");
              browser = await puppeteer.launch({
                headless: 'new',
                args: ['--no-sandbox','--disable-setuid-sandbox']
              });
              page = await browser.newPage();

              // Stage 1: Login
              console.log("Navigating to login page:", loginUrl);
              await page.goto(loginUrl, { waitUntil: 'networkidle2', timeout: 60000 });
              await safeScreenshot(page, `screenshots/pubby_home_${Date.now()}.png`);

              console.log("Filling in login credentials...");
              await page.type('input[name="email"]', username, { delay: 100 });
              await page.type('input[name="password"]', password, { delay: 100 });
              await safeScreenshot(page, `screenshots/pubby_credentials_filled_${Date.now()}.png`);

              console.log("Submitting login form...");
              await Promise.all([
                page.click('button[type="submit"]'),
                page.waitForNavigation({ waitUntil: 'networkidle2', timeout: 60000 })
              ]);
              await safeScreenshot(page, `screenshots/pubby_after_login_${Date.now()}.png`);

              // Stage 2: Verify login
              console.log("Verifying login status...");
              const dash = await page.$('a.logout, .dashboard');
              if (!dash) {
                console.warn("Login may have failed.");
                await safeScreenshot(page, `screenshots/pubby_login_failed_${Date.now()}.png`);
              }

              // Stage 3: Browse page
              console.log("Navigating to browse page:", browseUrl);
              await page.goto(browseUrl, { waitUntil: 'networkidle2', timeout: 60000 });
              await sleep(10000);
              await safeScreenshot(page, `screenshots/pubby_browse_${Date.now()}.png`);

              // Stage 4: Click Kindle Unlimited
              console.log("Clicking 'Kindle Unlimited' filter…");
              const kuClicked = await page.evaluate(() => {
                const tag = Array.from(document.querySelectorAll('.browsing-tag'))
                  .find(t => t.querySelector('.label')?.innerText.trim() === 'Kindle Unlimited');
                if (tag) { tag.click(); return true; }
                return false;
              });
              if (!kuClicked) console.error("ERROR: Kindle Unlimited filter not found");
              await sleep(5000);
              await safeScreenshot(page, `screenshots/pubby_kindle_unlimited_${Date.now()}.png`);

              // Stage 5: Click Most Snaps
              console.log("Clicking 'Most Snaps' filter…");
              const snapsClicked = await page.evaluate(() => {
                const tag = Array.from(document.querySelectorAll('.browsing-tag'))
                  .find(t => t.querySelector('.label')?.innerText.trim() === 'Most Snaps');
                if (tag) { tag.click(); return true; }
                return false;
              });
              if (!snapsClicked) console.error("ERROR: Most Snaps filter not found");
              await sleep(5000);
              await safeScreenshot(page, `screenshots/pubby_most_snaps_${Date.now()}.png`);

              // Stage 6: Wait for book list
              console.log("Waiting for books container…");
              await page.waitForSelector('.library-books-container', { visible: true, timeout: 60000 });
              await safeScreenshot(page, `screenshots/pubby_browse_loaded_${Date.now()}.png`);
              await sleep(5000);

              // Stage 7: Scroll to load more
              for (let i = 0; i < 3; i++) {
                console.log(`Scrolling iteration ${i+1}`);
                await page.evaluate(() => window.scrollBy(0, window.innerHeight));
                await sleep(3000);
                await safeScreenshot(page, `screenshots/pubby_scroll_${i+1}_${Date.now()}.png`);
              }

              // Stage 8: Extract recommended titles
              console.log("Extracting Recommended Books…");
              const recommended = await page.evaluate(() =>
                Array.from(document.querySelectorAll('.library-books-container .card .title-text'))
                  .map(el => el.innerText.trim())
              );
              console.log("Recommended Books:", recommended);
              await safeScreenshot(page, `screenshots/pubby_books_extracted_${Date.now()}.png`);

              // Stage 9: Extract timeline
              console.log("Extracting Activity Timeline…");
              const timeline = await page.evaluate(() =>
                Array.from(document.querySelectorAll('.timeline .event'))
                  .map(ev => ({
                    content: ev.querySelector('.content')?.innerText.trim() || '',
                    time: ev.querySelector('.time')?.innerText.trim() || ''
                  }))
              );
              console.log("Activity Timeline:", timeline);
              await safeScreenshot(page, `screenshots/pubby_activity_extracted_${Date.now()}.png`);

              // Stage 10: Pick a Kindle Unlimited book
              console.log("Scanning for Kindle Unlimited cards…");
              const kuHandle = await page.evaluateHandle(xpath => {
                const arr = [];
                const res = document.evaluate(
                  xpath, document, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null
                );
                for (let i = 0; i < res.snapshotLength; i++) {
                  arr.push(res.snapshotItem(i));
                }
                return arr;
              }, "//div[contains(@class,'card') and .//span[contains(@class,'verified-price') and normalize-space(text())='Kindle Unlimited']]");
              const kuProps = await kuHandle.getProperties();
              const kuEls = [];
              for (const p of kuProps.values()) {
                const el = p.asElement();
                if (el) kuEls.push(el);
              }
              if (kuEls.length > 0) {
                console.log("Clicking first KU card…");
                await kuEls[0].click();
                await sleep(2000);
                await safeScreenshot(page, `screenshots/pubby_ku_card_clicked_${Date.now()}.png`);

                console.log("Looking for 'Pick Book'…");
                const pickHandle = await page.evaluateHandle(xpath => {
                  const arr = [];
                  const res = document.evaluate(
                    xpath, document, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null
                  );
                  for (let i = 0; i < res.snapshotLength; i++) {
                    arr.push(res.snapshotItem(i));
                  }
                  return arr;
                }, "//div[contains(@class,'action-blue') and normalize-space(text())='Pick Book']");
                const pickProps = await pickHandle.getProperties();
                const pickEls = [];
                for (const p of pickProps.values()) {
                  const e = p.asElement();
                  if (e) pickEls.push(e);
                }
                if (pickEls.length > 0) {
                  console.log("Clicking 'Pick Book'…");
                  await pickEls[0].click();
                  await sleep(2000);
                  await safeScreenshot(page, `screenshots/pubby_pick_book_clicked_${Date.now()}.png`);
                } else {
                  console.warn("No 'Pick Book' found.");
                }
              } else {
                console.warn("No KU card found.");
              }

              // Stage 11: Wait for reader view and click the book
              console.log("Waiting for reader view to load…");
              await page.waitForSelector('.reader-container, .reader', { visible: true, timeout: 60000 });
              await safeScreenshot(page, `screenshots/pubby_reader_loaded_${Date.now()}.png`);

              console.log("Clicking the book in the reader…");
              const clickedReaderBook = await page.evaluate(() => {
                const book = document.querySelector('.reader .book, .reader-container .book');
                if (book) { book.click(); return true; }
                return false;
              });
              if (!clickedReaderBook) {
                console.error("ERROR: Could not click the book in the reader");
              } else {
                await safeScreenshot(page, `screenshots/pubby_reader_book_clicked_${Date.now()}.png`);
              }

              // Stage 12: Click 'View On Amazon'
              console.log("Clicking 'View On Amazon' button…");
              const clickedViewAmazon = await page.evaluate(() => {
                const btn = document.querySelector('.action.copy-amazon-link');
                if (btn) { btn.click(); return true; }
                return false;
              });
              if (!clickedViewAmazon) {
                console.error("ERROR: Could not click 'View On Amazon'");
              } else {
                await safeScreenshot(page, `screenshots/pubby_view_amazon_${Date.now()}.png`);
              }

            } catch (err) {
              console.error("Script error:", err.message);
            } finally {
              if (page) {
                try {
                  console.log("Saving final HTML…");
                  const html = await page.content();
                  fs.writeFileSync(`screenshots/pubby_final_page_${Date.now()}.html`, html);
                } catch (e) {
                  console.error("Failed saving HTML:", e.message);
                }
              }
              if (browser) await browser.close();
            }
          }

          (async () => {
            const loginUrl = process.env.PUBBY_LOGIN_URL;
            const browseUrl = process.env.PUBBY_BROWSE_URL;
            const username = process.env.PUBBY_USERNAME;
            const password = process.env.PUBBY_PASSWORD;
            if (!username || !password) {
              console.error("Missing credentials");
              process.exit(1);
            }
            await loginAndBrowse(loginUrl, browseUrl, username, password);
          })();
          EOL

      - name: Run Puppeteer script
        env:
          PUBBY_LOGIN_URL: "https://account.pubby.co/login"
          PUBBY_BROWSE_URL: "https://app.pubby.co/#/browse"
          PUBBY_USERNAME: ${{ secrets.PUBBY_USERNAME }}
          PUBBY_PASSWORD: ${{ secrets.PUBBY_PASSWORD }}
        run: |
          echo "Logging in to: $PUBBY_LOGIN_URL and navigating to: $PUBBY_BROWSE_URL"
          node scripts/pubby-login-and-browse.js | tee script_output.log

      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pubby-debug-artifacts
          path: |
            screenshots/
            *.log
          retention-days: 7
